Repository YAPP-19th/iOS-Team-2-Backend, pull requests merged in 2021-11, with the labels that each got.

#4 feat: project 기본 설정 추가
  .gitignore
  build.gradle
  src/main/java/com/yapp/project/BudiApplication.java
  src/main/java/com/yapp/project/TeamBuildingApplication.java
  src/main/java/com/yapp/project/common/entity/BaseEntity.java
  src/main/java/com/yapp/project/common/exception/ApiExceptionResult.java
  src/main/java/com/yapp/project/common/exception/ExceptionMessage.java
  src/main/java/com/yapp/project/common/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/project/common/exception/type/NotFoundException.java
  src/main/java/com/yapp/project/common/web/ApiResult.java
  src/main/java/com/yapp/project/common/web/LinkType.java
  src/main/java/com/yapp/project/common/web/ResponseMessage.java
  src/main/java/com/yapp/project/config/ApplicationConfig.java
  src/main/java/com/yapp/project/config/JpaConfig.java
  src/main/java/com/yapp/project/config/SwaggerConfig.java
  src/test/java/com/yapp/project/BudiApplicationTests.java
Labels: feature

#7 Feature/#5 post domain
  .gitignore
  build.gradle
  src/main/java/com/yapp/project/BudiApplication.java
  src/main/java/com/yapp/project/common/entity/BaseEntity.java
  src/main/java/com/yapp/project/common/exception/ApiExceptionResult.java
  src/main/java/com/yapp/project/common/exception/DtoValidationFailMessage.java
  src/main/java/com/yapp/project/common/exception/ExceptionMessage.java
  src/main/java/com/yapp/project/common/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/project/common/exception/type/FileUploadFailException.java
  src/main/java/com/yapp/project/common/exception/type/InvalidRequestBodyFieldException.java
  src/main/java/com/yapp/project/common/vo/Position.java
  src/main/java/com/yapp/project/common/vo/Skill.java
  src/main/java/com/yapp/project/common/web/ResponseMessage.java
  src/main/java/com/yapp/project/config/ApplicationConfig.java
  src/main/java/com/yapp/project/config/SwaggerConfig.java
  src/main/java/com/yapp/project/external/s3/S3Uploader.java
  src/main/java/com/yapp/project/joinedinfo/entity/JoinedInfo.java
  src/main/java/com/yapp/project/likepost/entity/LikePost.java
  src/main/java/com/yapp/project/member/entity/Member.java
  src/main/java/com/yapp/project/member/repository/MemberRepository.java
  src/main/java/com/yapp/project/post/controller/PostController.java
  src/main/java/com/yapp/project/post/controller/bundle/PostBundleConverter.java
  src/main/java/com/yapp/project/post/controller/bundle/RecruitingPositionBundle.java
  src/main/java/com/yapp/project/post/dto/request/PostCreateRequest.java
  src/main/java/com/yapp/project/post/dto/request/RecruitingPositionRequest.java
  src/main/java/com/yapp/project/post/dto/response/PostCreateResponse.java
  src/main/java/com/yapp/project/post/dto/response/PostInfoResponse.java
  src/main/java/com/yapp/project/post/dto/response/RecruitingStatusResponse.java
  src/main/java/com/yapp/project/post/entity/Post.java
  src/main/java/com/yapp/project/post/entity/RecruitingPosition.java
  src/main/java/com/yapp/project/post/entity/vo/PostCategory.java
  src/main/java/com/yapp/project/post/entity/vo/PostStatus.java
  src/main/java/com/yapp/project/post/repository/JoinedInfoRepository.java
  src/main/java/com/yapp/project/post/repository/PostRepository.java
  src/main/java/com/yapp/project/post/repository/RecruitingPositionRepository.java
  src/main/java/com/yapp/project/post/service/PostConverter.java
  src/main/java/com/yapp/project/post/service/PostService.java
  src/main/java/com/yapp/project/post/service/RecruitingPositionConverter.java
  src/main/resources/application.yml
  src/main/resources/banner.txt
  src/test/java/com/yapp/project/BudiApplicationTests.java
Labels: feature

#19 Feature/#15 post online
  src/main/java/com/yapp/project/common/exception/DtoValidationFailMessage.java
  src/main/java/com/yapp/project/common/exception/ExceptionMessage.java
  src/main/java/com/yapp/project/common/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/project/common/value/Position.java
  src/main/java/com/yapp/project/common/value/Skill.java
  src/main/java/com/yapp/project/post/controller/PostController.java
  src/main/java/com/yapp/project/post/dto/request/PostCreateRequest.java
  src/main/java/com/yapp/project/post/dto/request/RecruitingPositionRequest.java
  src/main/java/com/yapp/project/post/dto/response/PostInfoResponse.java
  src/main/java/com/yapp/project/post/entity/Post.java
  src/main/java/com/yapp/project/post/entity/value/OnlineStatus.java
  src/main/java/com/yapp/project/post/entity/value/PostCategory.java
  src/main/java/com/yapp/project/post/entity/value/PostStatus.java
  src/main/java/com/yapp/project/post/service/PostConverter.java
  src/main/java/com/yapp/project/post/service/PostService.java
  src/main/java/com/yapp/project/post/service/RecruitingPositionConverter.java
Labels: feature

#21 Feature/#20 post api update
  src/main/java/com/yapp/project/common/exception/ExceptionMessage.java
  src/main/java/com/yapp/project/common/value/Position.java
  src/main/java/com/yapp/project/common/value/RootPosition.java
  src/main/java/com/yapp/project/common/web/ResponseMessage.java
  src/main/java/com/yapp/project/post/controller/PostController.java
  src/main/java/com/yapp/project/post/dto/response/PostDeleteResponse.java
  src/main/java/com/yapp/project/post/dto/response/RecruitingStatusResponse.java
  src/main/java/com/yapp/project/post/entity/RecruitingPosition.java
  src/main/java/com/yapp/project/post/entity/value/PostStatus.java
  src/main/java/com/yapp/project/post/repository/JoinedInfoRepository.java
  src/main/java/com/yapp/project/post/repository/PostRepository.java
  src/main/java/com/yapp/project/post/repository/RecruitingPositionRepository.java
  src/main/java/com/yapp/project/post/service/PostConverter.java
  src/main/java/com/yapp/project/post/service/PostService.java
  src/main/java/com/yapp/project/post/service/RecruitingPositionConverter.java
Labels: feature

#22 Feature/#18 statuscode
  src/main/java/com/yapp/project/common/StatusCode.java
  src/main/java/com/yapp/project/common/exception/ApiExceptionResult.java
  src/main/java/com/yapp/project/common/exception/ExceptionMessage.java
  src/main/java/com/yapp/project/common/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/project/common/exception/status/ServerStatusCode.java
  src/main/java/com/yapp/project/common/exception/type/InvalidRequestBodyFieldException.java
  src/main/java/com/yapp/project/common/web/ApiResult.java
  src/main/java/com/yapp/project/common/web/ResponseMessage.java
  src/main/java/com/yapp/project/post/entity/RecruitingPosition.java
Labels: feature

#23 Feature/#6 oauth
  build.gradle
  src/main/java/com/yapp/project/common/web/ResponseMessage.java
  src/main/java/com/yapp/project/member/controller/AuthController.java
  src/main/java/com/yapp/project/member/controller/MemberController.java
  src/main/java/com/yapp/project/member/dto/JwtValidationResult.java
  src/main/java/com/yapp/project/member/dto/LoginRequest.java
  src/main/java/com/yapp/project/member/dto/LoginResponse.java
  src/main/java/com/yapp/project/member/repository/MemberRepository.java
  src/main/java/com/yapp/project/member/service/JwtService.java
  src/main/java/com/yapp/project/member/service/JwtUtil.java
  src/main/java/com/yapp/project/member/service/MemberService.java
Labels: feature

#30 Fix/#29 remove hateoas
  build.gradle
  src/main/java/com/yapp/project/common/web/ApiResult.java
  src/main/java/com/yapp/project/common/web/LinkType.java
  src/main/java/com/yapp/project/post/controller/PostController.java
Labels: 우선순위[하], fix

#32 fix: update swagger config for page
  src/main/java/com/yapp/project/config/SwaggerConfig.java
Labels: fix

#39 Feature/#37 post detail
  src/main/java/com/yapp/project/common/StatusCode.java
  src/main/java/com/yapp/project/common/exception/DtoValidationFailMessage.java
  src/main/java/com/yapp/project/common/exception/ExceptionMessage.java
  src/main/java/com/yapp/project/common/exception/GlobalExceptionHandler.java
  src/main/java/com/yapp/project/common/value/Position.java
  src/main/java/com/yapp/project/common/value/RootPosition.java
  src/main/java/com/yapp/project/common/value/Skill.java
  src/main/java/com/yapp/project/common/web/ResponseMessage.java
  src/main/java/com/yapp/project/config/SwaggerConfig.java
  src/main/java/com/yapp/project/member/service/JwtService.java
  src/main/java/com/yapp/project/post/controller/PostController.java
  src/main/java/com/yapp/project/post/controller/bundle/PostBundleConverter.java
  src/main/java/com/yapp/project/post/controller/bundle/RecruitingPositionBundle.java
  src/main/java/com/yapp/project/post/dto/request/PostCreateRequest.java
  src/main/java/com/yapp/project/post/dto/request/RecruitingPositionRequest.java
  src/main/java/com/yapp/project/post/dto/response/PostDetailResponse.java
  src/main/java/com/yapp/project/post/dto/response/PostSimpleResponse.java
  src/main/java/com/yapp/project/post/dto/response/TeamMemberResponse.java
  src/main/java/com/yapp/project/post/entity/Post.java
  src/main/java/com/yapp/project/post/entity/RecruitingPosition.java
  src/main/java/com/yapp/project/post/service/PostConverter.java
  src/main/java/com/yapp/project/post/service/PostService.java
Labels: feature

#41 Feature/#40 apply
  src/main/java/com/yapp/project/apply/controller/Applycontroller.java
  src/main/java/com/yapp/project/apply/dto/request/ApplyRequest.java
  src/main/java/com/yapp/project/apply/entity/Apply.java
  src/main/java/com/yapp/project/apply/entity/value/ApplyStatus.java
  src/main/java/com/yapp/project/apply/repository/ApplyRepository.java
  src/main/java/com/yapp/project/apply/service/ApplyConverter.java
  src/main/java/com/yapp/project/apply/service/ApplyService.java
  src/main/java/com/yapp/project/common/StatusCode.java
  src/main/java/com/yapp/project/common/exception/ExceptionMessage.java
  src/main/java/com/yapp/project/common/exception/type/IllegalRequestException.java
  src/main/java/com/yapp/project/common/web/ApiResult.java
  src/main/java/com/yapp/project/post/controller/PostController.java
  src/main/java/com/yapp/project/post/dto/response/RecruitingStatusResponse.java
  src/main/java/com/yapp/project/post/dto/response/TeamMemberResponse.java
  src/main/java/com/yapp/project/post/service/PostService.java
  src/main/java/com/yapp/project/post/service/RecruitingPositionConverter.java
Labels: feature

#42 Feature/#25 review
  src/main/java/com/yapp/project/common/StatusCode.java
  src/main/java/com/yapp/project/common/exception/ExceptionMessage.java
  src/main/java/com/yapp/project/common/web/ApiResult.java
  src/main/java/com/yapp/project/review/controller/CodeReviewHistoryController.java
  src/main/java/com/yapp/project/review/dto/request/CodeReviewInsertRequest.java
  src/main/java/com/yapp/project/review/dto/response/CodeReviewListResponse.java
  src/main/java/com/yapp/project/review/entity/CodeReviewHistory.java
  src/main/java/com/yapp/project/review/entity/TextReviewHistory.java
  src/main/java/com/yapp/project/review/entity/value/ReviewCode.java
  src/main/java/com/yapp/project/review/repository/CodeReviewHistoryRepossitory.java
  src/main/java/com/yapp/project/review/service/CodeReviewHistoryConverter.java
  src/main/java/com/yapp/project/review/service/CodeReviewHistoryService.java
Labels: feature
